{{- if and .Values.prometheus.enabled .Values.prometheus.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "timed.fullname" . }}-backend
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- if .Values.prometheus.extraLabels }}
    {{- .Values.prometheus.extraLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "timed.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  podMetricsEndpoints:
    - port: http
      {{- if .Values.prometheus.podMonitor.interval }}
      interval: {{ .Values.prometheus.podMonitor.interval }}
      {{- end }}
      path: "/prometheus/metrics"
      {{- if .Values.prometheus.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.prometheus.podMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .Values.prometheus.podMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.prometheus.podMonitor.relabelings | nindent 6 }}
      {{- end }}
{{- end }}
